name: Deploy FastAPI to ECS

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout
    - name: Checkout Code
      uses: actions/checkout@v3

    # AWS CLI 및 Docker Login
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 335386407661.dkr.ecr.ap-northeast-2.amazonaws.com


    # Docker Image Build 및 Push
    - name: Build and Push Docker Image
      run: |
        docker build -t fastapi-app .
        docker tag fastapi-app:latest 335386407661.dkr.ecr.ap-northeast-2.amazonaws.com/fastapi-app
        docker push 335386407661.dkr.ecr.ap-northeast-2.amazonaws.com/fastapi-app

    # ECS Update
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs-task-definition.json
        service: fastapi
        cluster: fastapi-cluster
        wait-for-service-stability: true
    